//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalBaseDeDatos.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_PACIENTES
    {
        public string Nombre_del_paciente { get; set; }
        public string CURP { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int Expediente { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string Alergias { get; set; }
        public string Ciudad { get; set; }
    }
}
